@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0




Project-up-|>Activitat
Task -up-|> Activitat
Project"1"*--->"*"Activitat
Task"1"-->"*"Interval

package java.util{
Observable o--up->Observer : Observers*
}
Clock---|>Observable
Interval..|>Observer

Interface Observer{
    +update(arg0 : Observable, arg1 : Object)
}
Abstract Observable{
    +addObserver(ob : Observer)
    +deleteObserver(ob : Observer)
    +setChanged()
    +notifyObservers(arg0 : Observable, arg1 : Object)

}
class Project {
    -Activitats[] : Activitat

    +Project(name : String)
    +TotalTime() : DateTimeFormater
    +addActivitat(t : Activitat)
    +removeActivitat(t : Activitat)
}
class Task{
    -Interval[] : Interval
    -initD : DateTimeFormater
    -finalD : DateTimeFormater


    +Task(name : String)
    +TotalTime() : DateTimeFormater
    +addInterval(i : Interval) : void
}

abstract Activitat{
    #name : String
    #project : Project

    +Activitat(name : String)
    +TotalTime() : DateTimeFormater
    +getName() : String
}
class Interval{
    -initD : DateTimeFormater
    -finalD : DateTimeFormater

    +Interval(initD : DateTimeFormater, finalD : DateTimeFormater)
    +getInitD() : DateTimeFormater
    +getFinalD() : DateTimeFormater
    +update()
}
class Clock{
    -timer : Timer
    -dateTime : DateTime
    +startTimer()
    -tick()
}


@enduml